### ISSUE TITLE
Random.Next(1, 100)

### ISSUE THREAD

**Issue by heliheli** [Drenalol/BDO_Simulator#1]
`var zatochil = ebanniyRandom.Next(1, 100);`
Это случайное число от 1 до 100, включая 1 и не включая 100.
`if (zatochil <= chance)`
Это проверка, прошел ли шанс. Шансы там от 1.5 до 100.

Тут несколько проблем:
1. чисел в диапазоне рандома 99, а не 100, например тот же 1 выпадает с шансом не 1/100, а 1/99. То есть стоит либо использовать Random.Next(0, 100) и сравнение '<', либо Random.Next(1, 101) и оставить '<='
2. дробные шансы не учитываются. Например, 1 и 1.5 будут срабатывать с одинаковым шансом. Учитывая, что там важны сотые и тысячные шанса, имеет смысл использовать, например Random.Next(1, 10001)

Это мое мнение, на точность не претендую, но рекомендую протестить - погонять в большом цикле некоторые события, и посмотреть, на сколько они будут соответствовать своему шансу.

**Comment by Drenalol** [comment]
Спасибо за наводки, исправил на Random.NextDouble(). Теперь должен поточнее считать шанс, хотя тыкал по миллионной точке в старом варианте - разницы никакой, хотя понимаю что было неправильно.

**Comment by heliheli** [comment]
Ну я погонял в цикле например 20% шанс, со старым кодом результаты были такие:
20,1864
20,19238
20,18843
20,19509
20,2305
20,18975
20,19569
20,20854
20,1989
20,20078

С новым кодом результаты такие:
20,00191
20,00162
20,00864
20,01256
20,00973
19,99566
20,01495
19,99396
19,99634
19,99779

Думаю заметна разница - почти 0.2%. Я бы еще все таки вместо <= использовал <, раз NextDouble включает 0 и не включает 1, но в целом уже не будет заметной разницы.
